### ISSUE TITLE
How to get the trained model?

### ISSUE THREAD

**Issue by hillaric** [YoungXIAO13/PoseFromShape#1]
Hello, congratulate to  you! You did a good job. I want to know how to download the file of the trained model ? I can not download it from the download_models.sh, can you help me? thank you for your help.

**Comment by YoungXIAO13** [comment]
Hi, thanks for noticing the issue, I've updated the download_models.sh and now you should be able to download the models.

**Comment by hillaric** [comment]
I have tried it, but it still not work.....and it shows some strange things

![image](https://user-images.githubusercontent.com/50513602/61186144-9663bc00-a694-11e9-8483-ba804cf1de2b.png)

**Comment by YoungXIAO13** [comment]
Can you try to open this link https://www.dropbox.com/sh/ibvy525qf2fnhy6/AAAFTZRnx3Guz1tsWjonHsfva?dl=0 and download the models manually?

**Comment by hillaric** [comment]
Thanks for your time, ca marche tres bien.
