### ISSUE TITLE
LINEMOD data error 

### ISSUE THREAD

**Issue by meghalD** [YoungXIAO13/PoseFromShape#10]
I downloaded LINEMOD dataset and then ran ply2obj.py create_annotation.py. they both run fine. But while running render.py for the same I get the following error :

Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libopenal.so.1: cannot open shared object file: No such file or directory

**Comment by YoungXIAO13** [comment]
Hi,

I think this problem results from the missing lib file in your system.

You can try ```sudo apt-get install libopenal1```
according to this [answer](https://askubuntu.com/questions/608418/error-while-loading-shared-libraries-libopenal-so-1-game-pacapong-in-ubuntu)

**Comment by meghalD** [comment]
> Hi,
> 
> I think this problem results from the missing lib file in your system.
> 
> You can try `sudo apt-get install libopenal1`
> according to this [answer](https://askubuntu.com/questions/608418/error-while-loading-shared-libraries-libopenal-so-1-game-pacapong-in-ubuntu)

it worked. Thanks
