### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by kartikgupta-at-anu** [YoungXIAO13/PoseFromShape#11]
I get this when I use your render scripts. Do you have any idea why this might be happening?

Its related to blender and happens when i import bpy.

Color management: using fallback mode for management
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory

**Comment by YoungXIAO13** [comment]
I also got this print when I was running the code, but it would not cause any problem in my rendering output. 
I think it might be just a warning from the blender library ?

**Comment by kartikgupta-at-anu** [comment]
no but when i run test script it says

renders = read_multiviwes(self.render_transform, render_example_path, self.view_num, self.tour, mutation)
read_multiviwes
    render_names = [name for name in os.listdir(render_example_path)]
FileNotFoundError: [Errno 2] No such file or directory: 'data/Pascal3D/Renders_semi_sphere/aeroplane/07/crop'

so i thought no rendering happened.

**Comment by YoungXIAO13** [comment]
I checked the rendering code, it works fine in Anaconda environment under Ubuntu 14.04 and 16.04 systems.

Another thing could cause this problem might be the ```off2obj.py``` script was not running correctly.
Could you check that the ```CAD``` folder contains all the necessary **.obj** files for rendering in the following format:
```CAD/category/cad_index.obj```

**Comment by kartikgupta-at-anu** [comment]
yeah that might be the issue.... thanks  :)

**Comment by kartikgupta-at-anu** [comment]
seems like I have been able to generate obj files for all objects except aeroplane and thus i cant get rendered images for that. are you able to generate obj files for aeroplane? I am not sure why i cant generate them.
