### ISSUE TITLE
shape and image feature dimension

### ISSUE THREAD

**Issue by kartikgupta-at-anu** [YoungXIAO13/PoseFromShape#12]
can you please tell me what are the specific shape and image feature dimensions used for the results in the paper, for different datasets? also can you indicate the training time for each dataset?

**Comment by YoungXIAO13** [comment]
For all the datasets used in the paper, the **image feature dimension** is 1024 from the last layer of ResNet-18, and the **shape feature dimension** is 256 for one rendered image and 1024 for pointcloud.

One thing to notice is that there are 12 rendered images but only one pointcloud used to represent each shape.

As for the training time, report on one Titan-X GPU with 4 workers:
Pascal3D: ~ 3 days.
ObjectNet3D: ~2 days.
ShapeNet: ~ 1 week.
You can **accelerate** the training by loading the data from a SSD if allowed.
