### ISSUE TITLE
CUDA error on running bash run/train_Pascal3D.sh

### ISSUE THREAD

**Issue by meghalD** [YoungXIAO13/PoseFromShape#13]
I just downloaded Pascal dataset and its pretrained models. I see in auxiliary/spec_file.txt CUDA 8 is being installed with python 3.6.
On running bash run/train_Pascal3D.sh I get CUDA VERSION ERROR 
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
Namespace(batch_size=16, bin_size=15, dataset='Pascal3D', decrease=200, img_feature_dim=1024, keypoint=False, lr=0.0001, model=None, n_epoch=300, novel=False, print_freq=50, random=True, random_range=0, shape='PointCloud', shape_dir='pointcloud', shape_feature_dim=1024, tour=2, view_num=12, workers=4)
Random Seed:  2019
/home/anaconda3/envs/PoseFromShape/lib/python3.6/site-packages/torch/cuda/__init__.py:115: UserWarning: 
    Found GPU0 Tesla V100-PCIE-16GB which requires CUDA_VERSION >= 9000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 8000. Please install the correct PyTorch binary
     using instructions from https://pytorch.org

**Comment by YoungXIAO13** [comment]
It seems that you have a Tesla V100 GPU which only supports CUDA version >= 9.0 and my cond environment uses pytorch with CUDA = 8.0

I think it might work out by reinstalling the pytorch in your conda env with
```conda install pytorch==1.0.1 torchvision==0.2.2 cudatoolkit=9.0 -c pytorch```
