### ISSUE TITLE
rotation_acc method for accuracy calculation

### ISSUE THREAD

**Issue by ajuric** [YoungXIAO13/PoseFromShape#14]
Hi Yang,

I have a couple of questions regarding the accuracy calculation.

1) I assume that [this line](https://github.com/YoungXIAO13/PoseFromShape/blob/master/auxiliary/utils.py#L151) converts the angles to [-180, 180]. But you only convert Elevation and In-plane rotation, and not Azimuth angle? Why?

2) [These calculations](https://github.com/YoungXIAO13/PoseFromShape/blob/master/auxiliary/utils.py#L130) convert from polar coordinates (Azimut, Elevation, In-plane rotation) to the rotation matrix? How did you arrive at these formulas? I tried it myself, didn't succeed. Also, I have tried to search for it on the web, also didn't find anything like that.

**Comment by ajuric** [comment]
Also, why converting to rotation matrix? Why not just looking at the difference between the angles without converting to rotation matrix?

**Comment by YoungXIAO13** [comment]
Hi ajuric,

For the first question, you can refer to #7 

And to obtain the [calculations](https://github.com/YoungXIAO13/PoseFromShape/blob/e0b8f44de34be88e6db1435d71dddd11d80eb565/auxiliary/utils.py#L130), I computed it by myself by using the equation **R=RZ(θ)RX(e−π/2)RZ(−a)** proposed in StarMap.
You can also refer to [their implementation](https://github.com/xingyizhou/StarMap/blob/26223a6c766eab3c22cddae87c375150f84f804d/tools/EvalCls.py#L20), which is much clearer compared to my implementation.

For the last question, the [angle distance between rotation matrix](http://www.boris-belousov.net/2016/12/01/quat-dist/) is a measure in SO(3), which is not the case if we just consider the difference between the angles.

**Comment by ajuric** [comment]
Thanks a lot!

**Comment by ajuric** [comment]
One more question about the angle distance between rotation matrices:

In the [blog](http://www.boris-belousov.net/2016/12/01/quat-dist/) you mention, it defines the R:
```
R = P * Q.T
```

I assumed that this multiplication is the real matrix multiplication, not the element-wise multiplication. But in the code, you do the element-wise multiplication, also without the transpose on the second matrix?

**Comment by YoungXIAO13** [comment]
Yes, I did an element-wise sum of the rotation matrix as the angle can be determined by:
**arccos((Trace(R) - 1) / 2)**, so I compute directly the trace of **R_pred * R_gt.T**.

More details can be found in [determine the angle](https://en.wikipedia.org/wiki/Rotation_matrix)

**Comment by ajuric** [comment]
I see, cool :+1:
