### ISSUE TITLE
using GT boxes to crop images

### ISSUE THREAD

**Issue by kartikgupta-at-anu** [YoungXIAO13/PoseFromShape#15]
Are you using GT boxes to crop the images in all the experiments in this paper? I am assuming StarMap, as well as all other baselines, do not use the cropped images and that is the reason for their worse performance. They need to simultaneously localize the object as well as estimate the viewpoint. Can you please correct me if I am wrong?

**Comment by YoungXIAO13** [comment]
Yes, I used GT boxes in all experiments as this paper focused on pose estimation on unseen objects providing the location in 2D image and its 3D cad model.

Meanwhile, other baselines on **Pascal3D** also used GT bounding boxes to crop the image, including [StarMap](https://github.com/xingyizhou/StarMap/blob/26223a6c766eab3c22cddae87c375150f84f804d/lib/datasets/ObjectNet3D.py#L61).

For results on **ObjectNet3D**, we've explained that **Xiang's** result is estimated from the detected boxed in the caption of Table-1.

**Comment by kartikgupta-at-anu** [comment]
oh yes thanks for correcting me.
