### ISSUE TITLE
The source of python-blender-2.77-py36_0.tar.bz2

### ISSUE THREAD

**Issue by ajuric** [YoungXIAO13/PoseFromShape#17]
Hi,

Could you please share where/how did you get the file [python-blender-2.77-py36_0.tar.bz2](https://github.com/YoungXIAO13/PoseFromShape/blob/master/auxiliary/python-blender-2.77-py36_0.tar.bz2)?

I have tried to install bpy manually by building the blender with bpy target, but have faced some difficulties ...

**Comment by YoungXIAO13** [comment]
Hi,

This file actually comes from one of my colleagues.

You can also try this [link](https://anaconda.org/kitsune.one/python-blender) with the correct python version to implement the blender, which is an updated version to the one I used.

**Comment by ajuric** [comment]
Thanks! I have searched a lot of stuff on the web, but apparently didn't find that one.

I actually tried to not to use conda, but OK :D

**Comment by ajuric** [comment]
Do you maybe know was that file built by building the blender with bpy target, or some other methods were used?

**Comment by YoungXIAO13** [comment]
Sorry, no idea about the source of this file.

BTW, it's better to install it in **conda** environment, I also tried **pip** install but it failed.

**Comment by ajuric** [comment]
Yes, I also tried installing with pip, but that gives errors ... so I switched to conda.

I just don't understand why making a bpy work is so mysterious :D

Thanks a lot!

**Comment by mmahdavian** [comment]
@YoungXIAO13 Is it possible for you to provide python blender for python3.7 too?

Thank You

**Comment by YoungXIAO13** [comment]
> @YoungXIAO13 Is it possible for you to provide python blender for python3.7 too?
> 
> Thank You

Sorry, I don't have the install package for that.
