### ISSUE TITLE
conda error 404 matplotlib not found

### ISSUE THREAD

**Issue by bach-zouk** [YoungXIAO13/PoseFromShape#2]
CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/matplotlib-3.0.2-py36h8a2030e_1.tar.bz2>
Elapsed: 00:00.317496
CF-RAY: 5038d1c95c3968d6-CDG

Thank you for your help!

**Comment by YoungXIAO13** [comment]
> CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url https://conda.anaconda.org/conda-forge/linux-64/matplotlib-3.0.2-py36h8a2030e_1.tar.bz2
> Elapsed: 00:00.317496
> CF-RAY: 5038d1c95c3968d6-CDG
> 
> Thank you for your help!

Have you encountered this problem while installing the conda env?
If yes, I think that you can delete this line
**https://conda.anaconda.org/conda-forge/linux-64/matplotlib-3.0.2-py36h8a2030e_1.tar.bz2** in spec-file.txt
then try to create conda env and use  **conda install -c conda-forge matplotlib** after the env is created and activated

**Comment by bach-zouk** [comment]
thank you. it works. I close it.
