### ISSUE TITLE
Detecting 6D pose of all objects in one image

### ISSUE THREAD

**Issue by mmahdavian** [YoungXIAO13/PoseFromShape#22]
Hi

I am trying to get 6D pose of all recognized objects in an image using your package. Do you have any codes for that? I mean I need the model to detect all of the objects in the image(for example when it is trained with ObjectNet3D I need it to recognize those objects)  and output its location and angle of the object. So I can make a cuboid from that object in the 3D space. Is your algorithm capable of this and Do you have any codes ready for doing this?

Thank You

**Comment by YoungXIAO13** [comment]
Hi,

Currently, this work focus on estimating the 3D rotation of an object, given its bounding box in the image.
So you might need to train an object detection model such as Faster R-CNN to first detect all the objects in an image, then use this repo to estimate the 3D rotation of each object contained in the predicted bounding boxes.

While detecting directly unseen objects is difficult, there is some work on few-shot object detection with network rapidely fine-tuned on a few labeled samples.
A good work can be found in [frustratingly simple few-shot object detection](https://github.com/ucbdrive/few-shot-object-detection)

**Comment by mmahdavian** [comment]
Thank you for your respond. Can your method provide Z position too? or it's only Euler angles and XY?

**Comment by YoungXIAO13** [comment]
Actually it's only Euler angles

**Comment by mmahdavian** [comment]
Thank You
