### ISSUE TITLE
object angles based on pointcloud model

### ISSUE THREAD

**Issue by mmahdavian** [YoungXIAO13/PoseFromShape#23]
Hi

Thanks for your great package. It has good features, but I think one thing is missing which can help people use your package much easier and attract more people to it. I need to input an image with only one object in it (such as a can) which has been seen while training and also pointcloud of that object and get the object angles as output. I know you are doing something similar in tesitng.py code for testing objects, but that code is complicated and it can be very useful. Is it possible for you to provide such a code? 

Thank You

**Comment by YoungXIAO13** [comment]
Hi,

Maybe you mean the [inference](https://github.com/YoungXIAO13/PoseFromShape/blob/master/inference.py)
