### ISSUE TITLE
about downloading checkpoints

### ISSUE THREAD

**Issue by Hautien** [YoungXIAO13/PoseFromShape#27]
i can't download your checkpoints from provided links, could you provide other links. 
thanks a lot!

**Comment by YoungXIAO13** [comment]
Hi @InceptionV5 

I've updated the [download_models.sh](https://github.com/YoungXIAO13/PoseFromShape/blob/master/model/download_models.sh), could you try with the new links?

**Comment by Hautien** [comment]
yes, it works.
thanks @YoungXIAO13
