### ISSUE TITLE
CGAL_LIBRARIES-NOTFOUND

### ISSUE THREAD

**Issue by Yunheng-Tian** [YoungXIAO13/PoseFromShape#28]
Hi, I'm following your instructions and try to find the executable_virtual_scanner, but here comes the error. I don't know why CGAL_LIBRARIES cannot be found. I'm working on Ubuntu 20.04

cmake -DCMAKE_BUILD_TYPE=Release ..
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: system 
-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: thread 
-- CGAL_INCLUDE_DIR=/usr/include
-- CGAL_LIBRARIES=CGAL_LIBRARIES-NOTFOUND
-- BOOST_THREAD_LIBRARIES=Boost::thread
-- GMP_LIBRARIES=/usr/lib/x86_64-linux-gnu/libgmp.so
-- CGAL not found.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: filesystem 
-- Configuring done
CMake Error at cpp/libvirtualscanner/CMakeLists.txt:15 (add_library):
   Target "virtualscanner" links to target "CGAL::CGAL" but the target was not found.  Perhaps a find_package() call is missing for   an IMPORTED target, or an ALIAS target is missing?

CMake Error at cpp/virtualscanner/CMakeLists.txt:5 (add_executable):
  Target "virtualscannerexe" links to target "CGAL::CGAL" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?

**Comment by YoungXIAO13** [comment]
Hi @Yunheng-Tian 

I'm not sure it this a bug specifically related to Ubuntu or some packages. If you just want to download point clouds for objects used in this work, you could use the command lines for [Pascal3D](https://github.com/YoungXIAO13/FewShotViewpoint/blob/115f65950b7eb338b6cf9dfe4485fac1ca44114b/data/Pascal3D/download_pascal3d.sh#L9) and [ObjectNet3D](https://github.com/YoungXIAO13/FewShotViewpoint/blob/115f65950b7eb338b6cf9dfe4485fac1ca44114b/data/ObjectNet3D/download_object3d.sh#L21)

And for more information about virtual scanner, you can look into [this repo](https://github.com/palanglois/O-CNN).

**Comment by Yunheng-Tian** [comment]
Hi @YoungXIAO13

Thank you anyway for providing your source code. As a beginner like me, it is of great help to have such an impression of how the project looks like.  I wish you all the best in your research career:)
