### ISSUE TITLE
error with train_pascal3D.sh

### ISSUE THREAD

**Issue by bach-zouk** [YoungXIAO13/PoseFromShape#4]
Hi,
Any help/suggestion would be very helpful.

File "training.py", line 93, in <module>
    train_loader = DataLoader(dataset_train, batch_size=opt.batch_size, shuffle=True, num_workers=opt.workers, drop_last=True)
  File "/home/abhishek/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "/home/abhishek/.local/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by YoungXIAO13** [comment]
Hi,
This issue is related to an error in **create_annotation.py** of Pascal3D.
I've updated this script and you can re-generate the annotation file **Pascal3D.txt** by going to the
directory (./data/Pascal3D/) and run ```python create_annotation.py```

**Comment by bach-zouk** [comment]
thank you. works now
