### ISSUE TITLE
Using predict for one image

### ISSUE THREAD

**Issue by yesimcemek** [YoungXIAO13/PoseFromShape#6]
I am trying to use one of your pre-trained models with an object I will use for my project. However, I couldn't find any instructions about how to use the models with another dataset. Could you please explain how to do that? I'm a little lost in your codes right now.

**Comment by YoungXIAO13** [comment]
I've added a part called **demo**, you can see how to apply trained network to new images picturing arbitrary 3D model. Basically, you need to get the right .obj file and generate multiviews from it, then you can save testing images in a directory and run inference to these images.

**Comment by yesimcemek** [comment]
Thank you for your quick reply. I tried the instructions you provided, but inference.sh gives an error since it couldn't find inference.py. If I'm not mistaken there is no script named inference.py. Could you please check the codes again?

**Comment by YoungXIAO13** [comment]
It's added now, sorry for the missing file at the first time : (
You can also train on more images generated from different models in order to get network that is more general.
Hope it'll help your project.

**Comment by yesimcemek** [comment]
Thank you, it works now.
