### ISSUE TITLE
PASCAL3D+ data link error 

### ISSUE THREAD

**Issue by meghalD** [YoungXIAO13/PoseFromShape#9]
I tried downloading data using data/prepare_data.sh but get the following error as the link is not working:
ftp://cs.stanford.edu/cs/cvgl/PASCAL3D+_release1.1.zip  cite cannot be reached and thus I cannot download the data. 
Is there a work around for the same  ?

**Comment by YoungXIAO13** [comment]
Hi,
I tried the download link and it works fine for me.
Another option is that you can download from the [official website](http://cvgl.stanford.edu/projects/pascal3d.html) directly by clicking the link.
Hopes it works for you.

**Comment by meghalD** [comment]
if I cannot download via code. I will be downloading the .zip files separately using the direct link. In which folder should that data be placed so as to work fine. Please suggest.
